language: ruby

rvm:
  - 2.6

os:
  - linux
  - osx

dist: xenial

branches:
  only:
    - gh-pages

before_install:
  - gem update --system

install:
  - gem install jekyll jekyll-paginate jekyll-sitemap jemoji octopress
  - octopress new post "Your post"

script:
  - jekyll clean
  - jekyll build