# Site settings.
url: https://blog.dikiaap.id
name: Diki Ananta
title: Blog · Diki Ananta
email: diki1aap@gmail.com
author: dikiaap
timezone: Asia/Jakarta
description: "Hi! I am Diki Ananta and I live in Indonesia. Little more about me. I'm a author, web developer, huge nerd, and <3 science."
social_username: dikiaap

# Build settings.
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins.
plugins:
  - jekyll-paginate