name: build

on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        ruby: 2.6
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install packages
        run: |
          gem update --system
          gem install jekyll jekyll-paginate jekyll-sitemap
      - name: Build blog.dikiaap.id
        run: |
          jekyll clean
          jekyll build