name: Build blog.dikiaap.id

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install packages
        run: |
          gem update --system
          gem install jekyll jekyll-paginate jekyll-sitemap
      - name: Build
        run: |
          jekyll clean
          jekyll build