name: schedule

on:
  schedule:
    # Monthly
    - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: [2.6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install packages
        run: |
          gem update --system
          gem install jekyll jekyll-paginate jekyll-sitemap
      - name: Build blog.dikiaap.id
        run: |
          jekyll clean
          jekyll build